version: '2'
services:
  laravel:
    build: 
      context: ./docker/laravel
      dockerfile: Dockerfile
    ports:
      - "7777:80"
      - "443:443"
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/fofo-api.conf:/etc/nginx/conf.d/fofo-api.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl
    links:
      - db:database
  lara-cli:
    build: 
      context: .
      dockerfile: ./docker/lara-cli/Dockerfile
    env_file: .env
    working_dir: /var/www/laravel
    volumes:
      - ./:/var/www/laravel
    links:
      - db:database
  db:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=fofo
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - ./.db/:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret